global:
  resolve_timeout: 5m
route:
  receiver: webhook_receiver
receivers:
    - name: webhook_receiver
      webhook_configs:
        - url: 'https://webhook.site/f2c9e063-fcce-4375-a672-e4e801c40743'
          send_resolved: false
